### ISSUE TITLE
Syntax not applied

### ISSUE THREAD

**Issue by owzim** [facelessuser/ApplySyntax#66]
Syntax setting
```
{
      "name": "JSON",
      "extensions": ["foo"]
}
```
When I open a file called `some.foo` nothing happens, the JSON syntax is not applied

This is what the console says:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 207, in on_load
    callback.on_load(v)
  File "ApplySyntax in ~/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 288, in on_load
  File "ApplySyntax in ~/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 312, in detect_syntax
  File "ApplySyntax in ~/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 392, in syntax_matches
  File "ApplySyntax in ~/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 480, in regexp_matches
  File "./re.py", line 156, in match
  File "./re.py", line 281, in _compile
  File "./sre_compile.py", line 491, in compile
  File "./sre_parse.py", line 747, in parse
  File "./sre_parse.py", line 359, in _parse_sub
  File "./sre_parse.py", line 568, in _parse
sre_constants.error: nothing to repeat
```

**Comment by facelessuser** [comment]
1. Make sure you are using the correct branch for ST3 or ST2.
2. Make sure you are defining your rules correctly
```js
        {
            "name": "JavaScript/JSON",
            "extensions": ["foo"]
        },
```

This is working fine for me on OSX with ST3.  Maybe you need to double check what you installed (I suggest Package Control when installing plugins).  Maybe restart SublimeText.  Double check that you haven't corrupted your settings file with invalid rules etc.  You could try a revert: https://www.sublimetext.com/docs/2/revert.html (ST2) or https://www.sublimetext.com/docs/3/revert.html (ST3).

I get no errors in the console, and when I use the rule I posted above it works fine for me on the latest OSX.

If you are able to provide some more info, I might be able to help more.

**Comment by owzim** [comment]
```JSON
"name": "JavaScript/JSON"
```
That solved it, thanks and sorry.

**Comment by facelessuser** [comment]
No problem.
